import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans", // optional but nice to have
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased bg-[#FFFFF2]`}>
        <div className="absolute flex justify-center inset-0 w-full h-full overflow-hidden">
          <div className="relative h-full w-full">
            <img
              src="/images/circle-vector.svg"
              alt="Logo"
              className="absolute bottom-0 left-1/2 transform -translate-x-1/2 z-10"
            />
            <img
              src="/images/blur.png"
              alt="Logo"
              className="absolute top-0 left-1/2 transform -translate-x-1/2 z-10"
            />
            <img
              src="/images/bg.png"
              alt="Logo"
              className="absolute top-0 left-1/2 transform -translate-x-1/2 z-0 "
            />
          </div>
        </div>
        <main className="relative z-20">{children}</main>
      </body>
    </html>
  );
}
